def complementing_dna_strand(dna):
    reverse = dna[::-1]
    reverse_complementary = ""
    for i in reverse:
        if i == "T":
            reverse_complementary += "A"
        if i == "A":
            reverse_complementary += "T"
        if i == "G":
            reverse_complementary += "C"
        if i == "C":
            reverse_complementary += "G"
    print(reverse_complementary)


if __name__ == '__main__':
    dna = "AGTAGATCATGTCTCTATGCCGCATCGTATGATATCCCTGACCTAGTCCAAATAGTTTTTCCAACGTATCCCGAGCTCAGACCCGGTCTTCCCGCACCGGGACGGAGTTTGTATCTGTCAAGATAAGTCTTAACTGTGATCGGTGCTTGCGGCTCGCCTAAAGTTGCCGTATAATATTAGAATATACACCCGGGGCAGAACGAGGCTGAAGTACCTTCCAATTATAAACAAGTACATAGCCCAGATAAGTACGCGCCCCACAGACTAGCAGTCACGTGCCCAGGTATTTACGCGGTGGATCTACCCGGTAAATAAACGAAATCTTCAGCGTAGGATCTGCCCCTGGTAGTGATTGTCCCGCCGATAAATACCATTTTAGCCGCCGCGCCTAGGCCTAGTACAGTGACGCTTAATGCACGCTTGCCTCGTCATCACACGGATCAGAAGAAGCAGCGCCAAAGTGCAGTTAGAGATTTGGCAGTCATGCAGTCCACCTTAAACGTGGACACGGGAGGAGACAGACTTCCTCTGGTCCGGGGCTATCCCCGCGTTGGTTGCTCATACCGGTGTTTGGCATCAATAGATTGAGTCTACCGTCGCGAAAGCAGCTCCCATGTCTCCTCCCCGCCCCCCTCTGTAGTGAAGCACTGGACTGCTGTGGCGTCCAGTAACACACGTTGAAGTGGAGTCTAAAGCTGCGTATAACGCCACATCCAATGTCAGCGGTATACTTCTCTTGTAAACGGCTGTGCCGTAATGCCTGGCATCGGGTAGATGGTCTACAGGCCGTGTTCATAAGAATAATTGCAACCAAACCTGAGGAAAAGTTCGCGTAACCGACTGGGTCCCCACCCTGAGGCGATGTAAGTTGCGTACAAGCTAAGCGCCCCCTTACGCCCGTGGCCCTCGATAGAAGTTCCCGACGACTGGGTACCGTCACTCCCTGCGAAGTGATGCCTCGCTTAAATAG"
    complementing_dna_strand(dna)
