def dna_to_rna(dna):
    rna = ""
    for i in dna:
        if i == "T":
            i = "U"
        rna += i
    print(rna)

if __name__ == '__main__':
    dna = "GATATATAAAACGGACAAATGGGTATTTGAACTCGCAAGACCTTACACGTGGCCGTCGGTACTAAAGACGTCCCCCAGTGCAAGAGAAGTGCACACTCCATCCTCTAACTATATCTGCTCTGCTTCGAGCGGCCCAATTTAGTGGTCAGCATTCCGGTGAGCCTGAGGAGCTAGTACTCGAAGCATGGAACACGTAGATGACTATTATCAGATAAATCATTTATAGGCGTAGTGACAAATATGCGGTCAGGTGCTTACGTGCTTGTCAGATGTAACGCTTCAATTCTCTACTGGAACCTGGACTTCGTTGTAGTAGTTATTGGGATCGGATTGCGGGACGTGCTCAACTTCCAAGGTCGCGGATTGTCGATCAACACAGGTGCGATGTGTAGCGCTATATATACCGCTAGTTAAATCTAGATGGTAGGACGTCATATTACTTTCACATTATCCACAAACGGTAAAGTCTGCTCCTCGGCGCCTGTCTACCTTCTTGCGCTCCTCCTCTGGACGGTCCAGCGTTTGAGATTGTTGGAGCCACGGACGCAGGAAATTATCAAATGCTCGTAGCAGACGCTCTTATTGGGTAATGGATTTCCATTAGCCTGTGCGAGCTTAGCGGTGGTGAGGGGTTTGGTCCGTGTAGTGAGTTATCCATGCTGTAGCCCGCGGTGACCGACACTCCTATAATTGTCTGTCGCCCGGGATCTAGGTCCACTATAGAACAGCAGTTTAATGCTACTTAGCTACTAACGCTGTAATTATGATCGGCGCACCCTGATCCCTTCCTAAGAGATACTTATAGGCGCCGAGGTGGCCGCTTAGCACTTAGTTCGTACGGGCTGTGTTTTCATATGTCCAAAATCATGGACGTAGTGCATGCTTATGGGGACACTCCCGGCACAAGCTGAGGTTGGACATCCCCTAACGTTGCTCAGGATAGGTTAGCCTTCAG"
    dna_to_rna(dna)
